/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "base-data_factory": () => import("@/views/base-data/factory/index.vue"),
  "base-data_line": () => import("@/views/base-data/line/index.vue"),
  "base-data_operation": () => import("@/views/base-data/operation/index.vue"),
  "base-data_product": () => import("@/views/base-data/product/index.vue"),
  "base-data_recipe": () => import("@/views/base-data/recipe/index.vue"),
  "base-data_route": () => import("@/views/base-data/route/index.vue"),
  "base-data_workshop": () => import("@/views/base-data/workshop/index.vue"),
  equipment_list: () => import("@/views/equipment/list/index.vue"),
  home: () => import("@/views/home/index.vue"),
  lot_detail: () => import("@/views/lot/detail/[id].vue"),
  lot_list: () => import("@/views/lot/list/index.vue"),
  quality_inspection: () => import("@/views/quality/inspection/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  wip_move: () => import("@/views/wip/move/index.vue"),
  "work-order_list": () => import("@/views/work-order/list/index.vue"),
};
