/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'base-data',
    path: '/base-data',
    component: 'layout.base',
    meta: {
      title: 'base-data',
      i18nKey: 'route.base-data'
    },
    children: [
      {
        name: 'base-data_factory',
        path: '/base-data/factory',
        component: 'view.base-data_factory',
        meta: {
          title: 'base-data_factory',
          i18nKey: 'route.base-data_factory'
        }
      },
      {
        name: 'base-data_line',
        path: '/base-data/line',
        component: 'view.base-data_line',
        meta: {
          title: 'base-data_line',
          i18nKey: 'route.base-data_line'
        }
      },
      {
        name: 'base-data_operation',
        path: '/base-data/operation',
        component: 'view.base-data_operation',
        meta: {
          title: 'base-data_operation',
          i18nKey: 'route.base-data_operation'
        }
      },
      {
        name: 'base-data_product',
        path: '/base-data/product',
        component: 'view.base-data_product',
        meta: {
          title: 'base-data_product',
          i18nKey: 'route.base-data_product'
        }
      },
      {
        name: 'base-data_recipe',
        path: '/base-data/recipe',
        component: 'view.base-data_recipe',
        meta: {
          title: 'base-data_recipe',
          i18nKey: 'route.base-data_recipe'
        }
      },
      {
        name: 'base-data_route',
        path: '/base-data/route',
        component: 'view.base-data_route',
        meta: {
          title: 'base-data_route',
          i18nKey: 'route.base-data_route'
        }
      },
      {
        name: 'base-data_workshop',
        path: '/base-data/workshop',
        component: 'view.base-data_workshop',
        meta: {
          title: 'base-data_workshop',
          i18nKey: 'route.base-data_workshop'
        }
      }
    ]
  },
  {
    name: 'equipment',
    path: '/equipment',
    component: 'layout.base',
    meta: {
      title: 'equipment',
      i18nKey: 'route.equipment'
    },
    children: [
      {
        name: 'equipment_board',
        path: '/equipment/board',
        component: 'view.equipment_board',
        meta: {
          title: 'equipment_board',
          i18nKey: 'route.equipment_board'
        }
      },
      {
        name: 'equipment_detail',
        path: '/equipment/detail/:id',
        component: 'view.equipment_detail',
        meta: {
          title: 'equipment_detail',
          i18nKey: 'route.equipment_detail'
        }
      },
      {
        name: 'equipment_list',
        path: '/equipment/list',
        component: 'view.equipment_list',
        meta: {
          title: 'equipment_list',
          i18nKey: 'route.equipment_list'
        }
      },
      {
        name: 'equipment_pm-plan',
        path: '/equipment/pm-plan',
        component: 'view.equipment_pm-plan',
        meta: {
          title: 'equipment_pm-plan',
          i18nKey: 'route.equipment_pm-plan'
        }
      },
      {
        name: 'equipment_pm-task',
        path: '/equipment/pm-task',
        component: 'view.equipment_pm-task',
        meta: {
          title: 'equipment_pm-task',
          i18nKey: 'route.equipment_pm-task'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'lot',
    path: '/lot',
    component: 'layout.base',
    meta: {
      title: 'lot',
      i18nKey: 'route.lot'
    },
    children: [
      {
        name: 'lot_detail',
        path: '/lot/detail/:id',
        component: 'view.lot_detail',
        props: true,
        meta: {
          title: 'lot_detail',
          i18nKey: 'route.lot_detail',
          hideInMenu: true
        }
      },
      {
        name: 'lot_list',
        path: '/lot/list',
        component: 'view.lot_list',
        meta: {
          title: 'lot_list',
          i18nKey: 'route.lot_list'
        }
      }
    ]
  },
  {
    name: 'quality',
    path: '/quality',
    component: 'layout.base',
    meta: {
      title: 'quality',
      i18nKey: 'route.quality'
    },
    children: [
      {
        name: 'quality_inspection',
        path: '/quality/inspection',
        component: 'view.quality_inspection',
        meta: {
          title: 'quality_inspection',
          i18nKey: 'route.quality_inspection'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    },
    children: [
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'wip',
    path: '/wip',
    component: 'layout.base',
    meta: {
      title: 'wip',
      i18nKey: 'route.wip'
    },
    children: [
      {
        name: 'wip_move',
        path: '/wip/move',
        component: 'view.wip_move',
        meta: {
          title: 'wip_move',
          i18nKey: 'route.wip_move'
        }
      },
      {
        name: 'wip_overview',
        path: '/wip/overview',
        component: 'view.wip_overview',
        meta: {
          title: 'wip_overview',
          i18nKey: 'route.wip_overview'
        }
      },
      {
        name: 'wip_station',
        path: '/wip/station',
        component: 'view.wip_station',
        meta: {
          title: 'wip_station',
          i18nKey: 'route.wip_station'
        }
      }
    ]
  },
  {
    name: 'work-order',
    path: '/work-order',
    component: 'layout.base',
    meta: {
      title: 'work-order',
      i18nKey: 'route.work-order'
    },
    children: [
      {
        name: 'work-order_list',
        path: '/work-order/list',
        component: 'view.work-order_list',
        meta: {
          title: 'work-order_list',
          i18nKey: 'route.work-order_list'
        }
      }
    ]
  }
];
